from src.definition.product_mapping import *

Beta_Charger = {
    "Beta_charger_MT7BLE": {
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "read_dusn": {
            "min": "0042007B000000000000",
            "max": "0042007BFFFFFFFFFFFF",
            "unit": "",
        },
        "MT_MODE": {"min": "", "max": "", "unit": ""},
        "ble_tx_ch0_neg20dB": {"min": -90, "max": -18, "unit": "dbm"},
        "ble_tx_ch0_6dB": {"min": -70, "max": -18, "unit": "dbm"},
        "ble_tx_ch18_neg20dB": {"min": -90, "max": -18, "unit": "dbm"},
        "ble_tx_ch18_6dB": {"min": -70, "max": -18, "unit": "dbm"},
        "ble_tx_ch36_neg20dB": {"min": -90, "max": -18, "unit": "dbm"},
        "ble_tx_ch36_6dB": {"min": -70, "max": -18, "unit": "dbm"},
        "ble_rx": {"min": 0, "max": 30, "unit": "%"},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_charger_MT7": {
        "TBB_UID": {"min": "", "max": "", "unit": "TBBUID"},
        "Detect_Dut": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "Initialize_Configs": {"min": "", "max": "", "unit": ""},
        "Device_Barcode": {"min": 17, "max": 17, "unit": ""},
        "QR_Scan": {"min": 17, "max": 17, "unit": ""},
        "Read_Station_ID": {"min": "", "max": "", "unit": "TBBUID"},
        "Read_DUSN": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "Read_MT_Mode": {"min": "", "max": "", "unit": ""},
        "Software_Revision": {"min": "", "max": "", "unit": ""},
        # "Software_Revision": {"min": "137.3.2", "max": "137.3.2", "unit": ""},
        "Application_ID_(MT)": {"min": "10", "max": "10", "unit": ""},
        "Holder_Presence": {"min": 1, "max": 1, "unit": ""},
        "USB_C_Info": {"min": 4, "max": 4, "unit": ""},
        "USB_Orientation_A": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "USB_Orientation_B": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "USB_CC_ADC_Side_A_Test": {"min": 379, "max": 544, "unit": ""},
        "USB_CC_ADC_Side_B_Test": {"min": 379, "max": 544, "unit": ""},
        "Key_Data": {"min": "", "max": "", "unit": ""},
        "Key_Length": {"min": 274, "max": 274, "unit": ""},
        "BIST_Test": {"min": "0000", "max": "0000", "unit": ""},
        "LED_Location_1_Off": {"min": 0, "max": 10, "unit": ""},
        "LED_Location_2_Off": {"min": 0, "max": 10, "unit": ""},
        "LED_Location_3_Off": {"min": 0, "max": 10, "unit": ""},
        "LED_Location_4_Off": {"min": 0, "max": 10, "unit": ""},
        "LED_Location_5_Off": {"min": 0, "max": 10, "unit": ""},
        "LED_Red_D303_Intensity": {"min": 13000, "max": 65555, "unit": ""},
        "LED_Red_D303_Red": {"min": 170, "max": 255, "unit": ""},
        "LED_Red_D303_Green": {"min": 0, "max": 50, "unit": ""},
        "LED_Red_D303_Blue": {"min": 0, "max": 50, "unit": ""},
        "LED_Red_D304_Intensity": {"min": 8000, "max": 65555, "unit": ""},
        "LED_Red_D304_Red": {"min": 170, "max": 255, "unit": ""},
        "LED_Red_D304_Green": {"min": 0, "max": 50, "unit": ""},
        "LED_Red_D304_Blue": {"min": 0, "max": 50, "unit": ""},
        "LED_White_D305_Intensity": {"min": 11500, "max": 65555, "unit": ""},
        "LED_White_D305_Red": {"min": 20, "max": 100, "unit": ""},
        "LED_White_D305_Green": {"min": 50, "max": 250, "unit": ""},
        "LED_White_D305_Blue": {"min": 20, "max": 150, "unit": ""},
        "LED_White_D306_Intensity": {"min": 11500, "max": 65555, "unit": ""},
        "LED_White_D306_Red": {"min": 20, "max": 100, "unit": ""},
        "LED_White_D306_Green": {"min": 50, "max": 250, "unit": ""},
        "LED_White_D306_Blue": {"min": 20, "max": 150, "unit": ""},
        "LED_White_D307_Intensity": {"min": 15000, "max": 65555, "unit": ""},
        "LED_White_D307_Red": {"min": 20, "max": 100, "unit": ""},
        "LED_White_D307_Green": {"min": 50, "max": 250, "unit": ""},
        "LED_White_D307_Blue": {"min": 20, "max": 150, "unit": ""},
        "LED_White_D308_Intensity": {"min": 10000, "max": 65555, "unit": ""},
        "LED_White_D308_Red": {"min": 20, "max": 100, "unit": ""},
        "LED_White_D308_Green": {"min": 50, "max": 250, "unit": ""},
        "LED_White_D308_Blue": {"min": 20, "max": 150, "unit": ""},
        "LED_White_D309_Intensity": {"min": 15000, "max": 65555, "unit": ""},
        "LED_White_D309_Red": {"min": 20, "max": 100, "unit": ""},
        "LED_White_D309_Green": {"min": 50, "max": 250, "unit": ""},
        "LED_White_D309_Blue": {"min": 20, "max": 150, "unit": ""},
        "LED_Amber_D310_Intensity": {"min": 4500, "max": 65555, "unit": ""},
        "LED_Amber_D310_Red": {"min": 20, "max": 150, "unit": ""},
        "LED_Amber_D310_Green": {"min": 50, "max": 250, "unit": ""},
        "LED_Amber_D310_Blue": {"min": 0, "max": 10, "unit": ""},
        "LED_White_D311_Intensity": {"min": 15000, "max": 65555, "unit": ""},
        "LED_White_D311_Red": {"min": 20, "max": 100, "unit": ""},
        "LED_White_D311_Green": {"min": 50, "max": 250, "unit": ""},
        "LED_White_D311_Blue": {"min": 20, "max": 150, "unit": ""},
        "BLE_Mac_Address_Retrieve": {"min": 17, "max": 17, "unit": ""},
        "Read_Model_Number": {"min": 5, "max": 5, "unit": ""},
        "DGS_Battery_Data": {"min": 22, "max": 28, "unit": ""},
        "Set_Battery_Configuration": {"min": "", "max": "", "unit": ""},
        "Read_Device_Battery_Config": {"min": "8", "max": "8", "unit": ""},
        "Button_Release_Test": {"min": "0001", "max": "0001", "unit": ""},
        "Button_Press_Test": {"min": "0000", "max": "0000", "unit": ""},
        "Hard_Reset_Test": {"min": "0000", "max": "0000", "unit": ""},
        "Codentify_Code_into_DUT": {"min": 14, "max": 14, "unit": ""},
        "Codentify_Code_in_DUT": {"min": 14, "max": 14, "unit": ""},
        "Battery_SN_in_DUT": {"min": 22, "max": 28, "unit": ""},
        "Battery_SN_into_DUT": {"min": "", "max": "", "unit": ""},
        "UTC_Time_Sync": {"min": -20, "max": 20, "unit": time_s},
        "Battery_Level_(in_MT_Mode)": {"min": 2.5, "max": 4.3, "unit": voltage_v},
        "Set_Device_in_MT_Mode": {"min": "0000", "max": "0000", "unit": ""},
        "Reset_DUT": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "Application_ID_(Exit_MT)": {"min": "10", "max": "10", "unit": ""},
        "MT_Mode_Status": {"min": "0000", "max": "0000", "unit": ""},
        "USB_Orientation_A_(Exit_MT)": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "USB_Orientation_B_(Exit_MT)": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "Holder_Charging_Status": {"min": "01", "max": "01", "unit": ""},
        "Device_System_Error": {"min": "00000000", "max": "00000000", "unit": ""},
        "Battery_Percentage": {"min": "", "max": "", "unit": percent},
        "Battery_Level_(Exit_MT)": {"min": 2.5, "max": 4.3, "unit": voltage_v},
        "BLE_Status": {"min": "0001", "max": "0001", "unit": ""},
        "Device_Ship_Status": {"min": "0102", "max": "0102", "unit": ""},
        "Retrieve_Sbl_Major_ID": {"min": "02", "max": "02", "unit": ""},
        "Retrieve_Ble_Stack_Version": {"min": "00000000010f0003", "max": "00000000010f0003", "unit": ""},
        "Overall_Test_Result": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_MT1_charger": {
        "Initialize_Configs": {"min": "", "max": "", "unit": ""},
        "Detect_Dut": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "Scan_Dusn": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "Eeprom_Blank_Check": {"min": 0, "max": 0, "unit": ""},
        "Write_HW_Reversion": {"min": "", "max": "", "unit": ""},
        "Verify_HW_revision": {"min": "0x01", "max": "0x01", "unit": ""},
        "Write_Dusn": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "Reset_DUT": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "Read_DUSN": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "write_auth_key": {"min": "", "max": "", "unit": ""},
        "read_auth_response0": {"min": "56437", "max": "56437", "unit": ""},
        "read_auth_response1": {"min": "14581", "max": "14581", "unit": ""},
        "BLE_Mac_Address_Retrieve": {"min": 17, "max": 17, "unit": ""},
        "BLE_Discovery": {"min": "", "max": "", "unit": ""},
        "Overall_Test_Result": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_charger_MT11C": {
        "Initialize_Configs": {"min": "", "max": "", "unit": ""},
        "QR_SCAN": {"min": 17, "max": 17, "unit": ""},
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "Detect_Dut": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "READ_CHARGER_PCBA_CODENTIFIER": {"min": 14, "max": 14, "unit": ""},
        "TEST_CAVITY": {"min": "", "max": "", "unit": ""},
        "LOG_BUILD_NUMBER": {"min": "", "max": "", "unit": ""},
        # "LOG_USER_NAME": {"min": "", "max": "", "unit": ""},
        "CHARGER_PCA_DUSN": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "QUERY_CHARGER_PCBA_EXIT_MT_MODE": {"min": "0000", "max": "0000", "unit": ""},
        "CONTROL_UNLOCK_DEVICE": {"min": "0000", "max": "0000", "unit": ""},
        # "CHARGER_SOFTWARE_ID_PARAMETER_LIST_VERSION": {"min": "137.2.3", "max": "137.2.3", "unit": ""},
        "CHARGER_SOFTWARE_ID_PARAMETER_LIST_VERSION": {"min": "", "max": "", "unit": ""},
        "CHARGER_PCA_TIME_SYNCHRONIZATION": {"min": -70, "max": 70, "unit": ""},
        "CHARGER_PCA_DUSN_AFTER_RESET": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "QUERY_SELF_TEST_RESULT": {"min": "0000", "max": "0000", "unit": ""},
        "CHARGER_VBATT_VOLTAGE_INITIAL": {"min": 3.0, "max": 4.3, "unit": voltage_v},
        "CHARGER_VBATT_VOLTAGE_PERCENT_INITIAL": {
            "min": 0,
            "max": 30,
            "unit": percent,
        },
        "MT11C_LIMITS_LOGGING": {"min": 29, "max": 30, "unit": percent},
        "VBATT_WITHIN_LIMITS_LOGGING": {"min": 29, "max": 30, "unit": percent},
        "CHARGER_VBATT_VOLTAGE_AFTER_INITAL": {
            "min": 3.0,
            "max": 4.3,
            "unit": voltage_v,
        },
        "CHARGER_VBATT_VOLTAGE_PERCENT_AFTER_INITIAL": {
            "min": 29,
            "max": 30,
            "unit": percent,
        },
        "CHARGER_PCA_DUSN_AFTER_TEST": {"min": "0042007B000000000000", "max": "0042007BFFFFFFFFFFFF", "unit": ""},
        "Stop_Charging": {"min": "3002", "max": "3002", "unit": ""},
        "SET_CHARGER_LOCK_SHIP_MODE": {"min": "0102", "max": "0102", "unit": ""},
        "QUERY_CHARGER_LOCK_SHIP_STATUS": {"min": "0102", "max": "0102", "unit": ""},
        "Overall_Test_Result": {"min": "0", "max": "0", "unit": "TR"},
    },
}
Hermes_Mid = {
    "Beta_charger_MT7BLE": {
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "read_dusn": {
            "min": "0033006A000000000000",
            "max": "0033006AFFFFFFFFFFFF",
            "unit": "",
        },
        "MT_MODE": {"min": "", "max": "", "unit": ""},
        "ble_tx_ch0_neg20dB": {"min": -90, "max": -18, "unit": "dbm"},
        "ble_tx_ch0_6dB": {"min": -70, "max": -18, "unit": "dbm"},
        "ble_tx_ch18_neg20dB": {"min": -90, "max": -18, "unit": "dbm"},
        "ble_tx_ch18_6dB": {"min": -70, "max": -18, "unit": "dbm"},
        "ble_tx_ch36_neg20dB": {"min": -90, "max": -18, "unit": "dbm"},
        "ble_tx_ch36_6dB": {"min": -70, "max": -18, "unit": "dbm"},
        "ble_rx": {"min": 0, "max": 30, "unit": "%"},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },

}
Hermes_Prime = {
    "Beta_charger_MT7BLE": {
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "read_dusn": {
            "min": "00330069000000000000",
            "max": "00330069FFFFFFFFFFFF",
            "unit": "",
        },
        "MT_MODE": {"min": "", "max": "", "unit": ""},
        "ble_tx_ch0_neg20dB": {"min": -90, "max": -18, "unit": "dbm"},
        "ble_tx_ch0_6dB": {"min": -70, "max": -18, "unit": "dbm"},
        "ble_tx_ch18_neg20dB": {"min": -90, "max": -18, "unit": "dbm"},
        "ble_tx_ch18_6dB": {"min": -70, "max": -18, "unit": "dbm"},
        "ble_tx_ch36_neg20dB": {"min": -90, "max": -18, "unit": "dbm"},
        "ble_tx_ch36_6dB": {"min": -70, "max": -18, "unit": "dbm"},
        "ble_rx": {"min": 0, "max": 30, "unit": "%"},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },

}
Hermes_Holder = {
    "Beta_holder_MT7CTS": {
        "start_test": {"min": "", "max": "", "unit": ""},
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "scan_barcode": {"min": "", "max": "", "unit": ""},
        "dusn_control": {
            "min": "00390066000000000000",
            "max": "00390066FFFFFFFFFFFF",
            "unit": "",
        },
        "screen_touch": {"min": 25, "max": 65535, "unit": ""},
        "led_r": {"min": "", "max": "", "unit": ""},
        "led_l": {"min": "", "max": "", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": ""},
    },
    "Beta_holder_MT7LED": {
        "Start_Button": {"min": "", "max": "", "unit": ""},
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "SCAN_VSN": {"min": "", "max": "", "unit": ""},
        "LOG_BUILD_NUMBER": {"min": "", "max": "", "unit": ""},
        "CONTROL_PCA_DUSN": {
            "min": "00390066000000000000",
            "max": "00390066FFFFFFFFFFFF",
            "unit": "",
        },
        "ENGINE_PCA_DUSN": {
            "min": "00290063000000000000",
            "max": "00290063FFFFFFFFFFFF",
            "unit": "",
        },
        "CONTROL_MT_MODE_STATE": {"min": "", "max": "", "unit": ""},
        "QUERY_DGS_LENS_COLOR": {"min": "", "max": "", "unit": ""},
        "PIL_LENS_COLOR": {"min": "", "max": "", "unit": ""},
        "COMPARE_COLOR_RESULT": {"min": "", "max": "", "unit": ""},
        "QUERY_EXISTING_CONFIGURATION_CODE": {"min": "", "max": "", "unit": ""},
        "WRITE_NVCM_CONFIGURATION_CODE": {"min": "", "max": "", "unit": ""},
        "QUERY_NVCM_CONFIGURATION_CODE": {"min": "", "max": "", "unit": ""},
        "WRITE_NVCM_LED_BRIGHTNESS": {"min": "", "max": "", "unit": ""},
        "QUERY_NVCM_LED_BRIGHTNESS": {"min": "", "max": "", "unit": ""},
        "R1_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R1_LED_GREEN": {"min": 15, "max": 210, "unit": ""},
        "R1_LED_BLUE": {"min": 15, "max": 190, "unit": ""},
        "R1_LED_INTENSITY": {"min": 15, "max": 220, "unit": ""},
        "R2_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "R2_LED_GREEN": {"min": 30, "max": 220, "unit": ""},
        "R2_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R2_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R3_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R3_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R3_LED_BLUE": {"min": 15, "max": 210, "unit": ""},
        "R3_LED_INTENSITY": {"min": 15, "max": 220, "unit": ""},
        "R4_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R4_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R4_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R4_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R5_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R5_LED_GREEN": {"min": 30, "max": 210, "unit": ""},
        "R5_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R5_LED_INTENSITY": {"min": 30, "max": 210, "unit": ""},
        "R6_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R6_LED_GREEN": {"min": 30, "max": 220, "unit": ""},
        "R6_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R6_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "R7_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R7_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R7_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R7_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R8_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "R8_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "R8_LED_BLUE": {"min": 30, "max": 220, "unit": ""},
        "R8_LED_INTENSITY": {"min": 40, "max": 220, "unit": ""},
        "R9_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R9_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R9_LED_BLUE": {"min": 15, "max": 190, "unit": ""},
        "R9_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R10_LED_RED": {"min": 15, "max": 190, "unit": ""},
        "R10_LED_GREEN": {"min": 15, "max": 180, "unit": ""},
        "R10_LED_BLUE": {"min": 15, "max": 170, "unit": ""},
        "R10_LED_INTENSITY": {"min": 15, "max": 180, "unit": ""},
        "R11_LED_RED": {"min": 15, "max": 200, "unit": ""},
        "R11_LED_GREEN": {"min": 15, "max": 200, "unit": ""},
        "R11_LED_BLUE": {"min": 15, "max": 180, "unit": ""},
        "R11_LED_INTENSITY": {"min": 20, "max": 210, "unit": ""},
        "R12_LED_RED": {"min": 20, "max": 210, "unit": ""},
        "R12_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "R12_LED_BLUE": {"min": 30, "max": 200, "unit": ""},
        "R12_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "R13_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R13_LED_GREEN": {"min": 20, "max": 210, "unit": ""},
        "R13_LED_BLUE": {"min": 20, "max": 190, "unit": ""},
        "R13_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R14_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R14_LED_GREEN": {"min": 30, "max": 220, "unit": ""},
        "R14_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R14_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "R15_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R15_LED_GREEN": {"min": 30, "max": 210, "unit": ""},
        "R15_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R15_LED_INTENSITY": {"min": 20, "max": 210, "unit": ""},
        "R16_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R16_LED_GREEN": {"min": 30, "max": 200, "unit": ""},
        "R16_LED_BLUE": {"min": 20, "max": 190, "unit": ""},
        "R16_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R17_LED_RED": {"min": 15, "max": 200, "unit": ""},
        "R17_LED_GREEN": {"min": 20, "max": 200, "unit": ""},
        "R17_LED_BLUE": {"min": 15, "max": 180, "unit": ""},
        "R17_LED_INTENSITY": {"min": 20, "max": 200, "unit": ""},
        "R18_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "R18_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "R18_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R18_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R19_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R19_LED_GREEN": {"min": 15, "max": 220, "unit": ""},
        "R19_LED_BLUE": {"min": 15, "max": 190, "unit": ""},
        "R19_LED_INTENSITY": {"min": 15, "max": 210, "unit": ""},
        "R20_LED_RED": {"min": 15, "max": 180, "unit": ""},
        "R20_LED_GREEN": {"min": 15, "max": 180, "unit": ""},
        "R20_LED_BLUE": {"min": 15, "max": 150, "unit": ""},
        "R20_LED_INTENSITY": {"min": 15, "max": 190, "unit": ""},
        "L1_LED_RED": {"min": 20, "max": 210, "unit": ""},
        "L1_LED_GREEN": {"min": 40, "max": 210, "unit": ""},
        "L1_LED_BLUE": {"min": 30, "max": 210, "unit": ""},
        "L1_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "L2_LED_RED": {"min": 15, "max": 180, "unit": ""},
        "L2_LED_GREEN": {"min": 15, "max": 190, "unit": ""},
        "L2_LED_BLUE": {"min": 15, "max": 170, "unit": ""},
        "L2_LED_INTENSITY": {"min": 15, "max": 180, "unit": ""},
        "L3_LED_RED": {"min": 15, "max": 200, "unit": ""},
        "L3_LED_GREEN": {"min": 30, "max": 210, "unit": ""},
        "L3_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "L3_LED_INTENSITY": {"min": 40, "max": 220, "unit": ""},
        "L4_LED_RED": {"min": 15, "max": 170, "unit": ""},
        "L4_LED_GREEN": {"min": 20, "max": 180, "unit": ""},
        "L4_LED_BLUE": {"min": 15, "max": 160, "unit": ""},
        "L4_LED_INTENSITY": {"min": 20, "max": 170, "unit": ""},
        "L5_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "L5_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "L5_LED_BLUE": {"min": 30, "max": 220, "unit": ""},
        "L5_LED_INTENSITY": {"min": 40, "max": 220, "unit": ""},
        "L6_LED_RED": {"min": 15, "max": 180, "unit": ""},
        "L6_LED_GREEN": {"min": 15, "max": 180, "unit": ""},
        "L6_LED_BLUE": {"min": 15, "max": 170, "unit": ""},
        "L6_LED_INTENSITY": {"min": 15, "max": 190, "unit": ""},
        "L7_LED_RED": {"min": 20, "max": 210, "unit": ""},
        "L7_LED_GREEN": {"min": 40, "max": 210, "unit": ""},
        "L7_LED_BLUE": {"min": 30, "max": 200, "unit": ""},
        "L7_LED_INTENSITY": {"min": 40, "max": 210, "unit": ""},
        "OFF_LED_RED": {"min": 0, "max": 3, "unit": ""},
        "OFF_LED_GREEN": {"min": 0, "max": 3, "unit": ""},
        "OFF_LED_BLUE": {"min": 0, "max": 3, "unit": ""},
        "OFF_LED_INTENSITY": {"min": 0, "max": 3, "unit": ""},
        "SEGMENT_DIM_CHECK_1": {"min": 0, "max": 50, "unit": ""},
        "SEGMENT_DIM_CHECK_2": {"min": 0, "max": 50, "unit": ""},
        "RING_LED_LEAKAGE": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_1": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_2": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_3": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_4": {"min": 0, "max": 10, "unit": ""},
        "LED_POSITION_1": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_2": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_3": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_4": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_5": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_6": {"min": "", "max": "", "unit": ""},
        "SET_CONTROL_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "READ_CONTROL_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "SET_ENGINE_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "READ_ENGINE_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_holder_MT7VC": {
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "write_codentify_code_control": {"min": "", "max": "", "unit": ""},
        "write_codentify_code_engine": {"min": "", "max": "", "unit": ""},
        "init_motor": {"min": "True", "max": "True", "unit": ""},
        "detect_dut": {"min": "XXXXXXXX", "max": "XXXXXXXX", "unit": ""},
        "BATTERY_LEVEL_TEST": {"min": 2500, "max": 4200, "unit": voltage_mv},
        "READ_CODENTIFY": {"min": "", "max": "", "unit": ""},
        "HAPTICS_OFF_TEST": {"min": 0, "max": 140, "unit": acceleration},
        "READ_DUSN": {"min": "00390066000400000000", "max": "003900660004FFFFFFFF", "unit": ""},
        "ACC_X_TEST": {"min": 0, "max": 300, "unit": acceleration},
        "ACC_Y_TEST": {"min": 0, "max": 300, "unit": acceleration},
        "ACC_Z_TEST": {"min": 700, "max": 1300, "unit": acceleration},
        "ANGULAR_X_TEST": {"min": 0, "max": 100, "unit": "mDPS"},
        "ANGULAR_Y_TEST": {"min": 0, "max": 100, "unit": "mDPS"},
        "ANGULAR_Z_TEST": {"min": 0, "max": 100, "unit": "mDPS"},
        "UNTOUCH0_TEST": {"min": 0, "max": 65535, "unit": "ADC"},
        "UNTOUCH1_TEST": {"min": 0, "max": 65535, "unit": "ADC"},
        "UNTOUCH2_TEST": {"min": 0, "max": 65535, "unit": "ADC"},
        "BUTTON0_TEST": {"min": 25, "max": 200, "unit": "ADC"},
        "BUTTON1_TEST": {"min": 25, "max": 200, "unit": "ADC"},
        "BUTTON2_TEST": {"min": 25, "max": 200, "unit": "ADC"},
        "HAPTICS_ON_TEST": {"min": 500, "max": 3050, "unit": acceleration},
        # "HAPTICS_ON_TEST": {"equal": 'True', "unit": ""},
        "EXIT_MT_MODE": {"min": 0, "max": 0, "unit": ""},
        "PRECHECK_MT_MODE": {"min": "beef", "max": "beef", "unit": ""},
        "READ_TEMPERATURE": {"min": 15, "max": 40, "unit": temperature},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_holder_MT11C": {
        "TBBUID": {"min": "", "max": "", "unit": ""},
        "TEST_CAVITY": {"min": "", "max": "", "unit": ""},
        "CONTROL_PCA_DUSN": {"min": "00390066000400000000", "max": "003900660004FFFFFFFF", "unit": ""},
        "ENGINE_PCA_DUSN": {"min": "00290063000400000000", "max": "002900630004FFFFFFFF", "unit": ""},
        "CHECK_CODENTIFY_CODE_CONTROL": {"min": "", "max": "", "unit": ""},
        "CHECK_CODENTIFY_CODE_ENGINE": {"min": "", "max": "", "unit": ""},
        "CONTROL_PCA_TIME_SYNCHRONIZATION": {"min": -20, "max": 20, "unit": time_s},
        "BATTERY_LEVEL": {"min": 28, "max": 30, "unit": percent},  # need upd
        "CONTROL_PCA_MT_STATUS": {"min": "0000", "max": "0000", "unit": ""},
        "ENGINE_PCA_MT_STATUS": {"min": "0000", "max": "0000", "unit": ""},
        "CONTROL_PCA_SW_ID": {"min": 0, "max": 0, "unit": ""},
        "ENGINE_PCA_SW_ID": {"min": 1, "max": 1, "unit": ""},
        "CONTROL_LOCK_MODE_BEFORE": {"min": "0000", "max": "0000", "unit": ""},
        "STOP_CHARGING": {"min": "True", "max": "True", "unit": ""},
        "HEATING_STATUS": {"min": "True", "max": "True", "unit": ""},
        "CONTROL_SHIP_MODE_AFTER": {"min": "0102", "max": "0102", "unit": ""},
        "check_ship_mode": {"min": "True", "max": "True", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_MT1_holder_control": {
        "TBBUID": {"min": "", "max": "", "unit": ""},
        "mt1_ask_question": {"equal": "True", "unit": ""},
        "detect_dut": {"equal": "XXXXXXXX", "unit": ""},
        "write_dusn_control": {"equal": "0041007aFFFFFFFFFFFF", "unit": ""},
        "write_dusn_engine": {"equal": "00290063FFFFFFFFFFFF", "unit": ""},
        "write_authentication_key_control": {"equal": "True", "unit": ""},
        "write_authentication_key_engine": {"equal": "True", "unit": ""},
        "check_authentication_control_key0": {"equal": "44988", "unit": ""},
        "check_authentication_control_key1": {"equal": "7116", "unit": ""},
        "check_authentication_engine_key0": {"equal": "56001", "unit": ""},
        "check_authentication_engine_key1": {"equal": "30164", "unit": ""},
        "fuel_program": {"equal": "True", "unit": ""},
        "fuel_functional_test": {"equal": "True", "unit": ""},
        "OVERALL_TEST_RESULT": {"equal": "0", "unit": "TR"},
    },
}
Beta_Holder = {
    "Beta_MT1_holder_control": {
        "TBBUID": {"min": "", "max": "", "unit": ""},
        "mt1_ask_question": {"equal": "True", "unit": ""},
        "detect_dut": {"equal": "XXXXXXXX", "unit": ""},
        "write_dusn_control": {"equal": "0041007aFFFFFFFFFFFF", "unit": ""},
        "write_dusn_engine": {"equal": "00290063FFFFFFFFFFFF", "unit": ""},
        "write_authentication_key_control": {"equal": "True", "unit": ""},
        "write_authentication_key_engine": {"equal": "True", "unit": ""},
        "check_authentication_control_key0": {"equal": "44988", "unit": ""},
        "check_authentication_control_key1": {"equal": "7116", "unit": ""},
        "check_authentication_engine_key0": {"equal": "56001", "unit": ""},
        "check_authentication_engine_key1": {"equal": "30164", "unit": ""},
        "fuel_program": {"equal": "True", "unit": ""},
        "fuel_functional_test": {"equal": "True", "unit": ""},
        "OVERALL_TEST_RESULT": {"equal": "0", "unit": "TR"},
    },
    "Beta_holder_MT7CTS": {
        "start_test": {"min": "", "max": "", "unit": ""},
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "scan_barcode": {"min": "", "max": "", "unit": ""},
        "dusn_control": {
            "min": "0041007A000000000000",
            "max": "0041007AFFFFFFFFFFFF",
            "unit": "",
        },
        "screen_touch": {"min": 25, "max": 65535, "unit": ""},
        "led_r": {"min": "", "max": "", "unit": ""},
        "led_l": {"min": "", "max": "", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": ""},
    },
    "Beta_holder_MT7LED": {
        "Start_Button": {"min": "", "max": "", "unit": ""},
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "SCAN_VSN": {"min": "", "max": "", "unit": ""},
        "LOG_BUILD_NUMBER": {"min": "", "max": "", "unit": ""},
        "CONTROL_PCA_DUSN": {
            "min": "0041007a000000000000",
            "max": "0041007aFFFFFFFFFFFF",
            "unit": "",
        },
        "ENGINE_PCA_DUSN": {
            "min": "00290063000000000000",
            "max": "00290063FFFFFFFFFFFF",
            "unit": "",
        },
        "CONTROL_MT_MODE_STATE": {"min": "", "max": "", "unit": ""},
        "QUERY_DGS_LENS_COLOR": {"min": "", "max": "", "unit": ""},
        "PIL_LENS_COLOR": {"min": "", "max": "", "unit": ""},
        "COMPARE_COLOR_RESULT": {"min": "", "max": "", "unit": ""},
        "QUERY_EXISTING_CONFIGURATION_CODE": {"min": "", "max": "", "unit": ""},
        "WRITE_NVCM_CONFIGURATION_CODE": {"min": "", "max": "", "unit": ""},
        "QUERY_NVCM_CONFIGURATION_CODE": {"min": "", "max": "", "unit": ""},
        "WRITE_NVCM_LED_BRIGHTNESS": {"min": "", "max": "", "unit": ""},
        "QUERY_NVCM_LED_BRIGHTNESS": {"min": "", "max": "", "unit": ""},
        "R1_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R1_LED_GREEN": {"min": 15, "max": 210, "unit": ""},
        "R1_LED_BLUE": {"min": 15, "max": 190, "unit": ""},
        "R1_LED_INTENSITY": {"min": 15, "max": 220, "unit": ""},
        "R2_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "R2_LED_GREEN": {"min": 30, "max": 220, "unit": ""},
        "R2_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R2_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R3_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R3_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R3_LED_BLUE": {"min": 15, "max": 210, "unit": ""},
        "R3_LED_INTENSITY": {"min": 15, "max": 220, "unit": ""},
        "R4_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R4_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R4_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R4_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R5_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R5_LED_GREEN": {"min": 30, "max": 210, "unit": ""},
        "R5_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R5_LED_INTENSITY": {"min": 30, "max": 210, "unit": ""},
        "R6_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R6_LED_GREEN": {"min": 30, "max": 220, "unit": ""},
        "R6_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R6_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "R7_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R7_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R7_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R7_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R8_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "R8_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "R8_LED_BLUE": {"min": 30, "max": 220, "unit": ""},
        "R8_LED_INTENSITY": {"min": 40, "max": 220, "unit": ""},
        "R9_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R9_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R9_LED_BLUE": {"min": 15, "max": 190, "unit": ""},
        "R9_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R10_LED_RED": {"min": 15, "max": 190, "unit": ""},
        "R10_LED_GREEN": {"min": 15, "max": 180, "unit": ""},
        "R10_LED_BLUE": {"min": 15, "max": 170, "unit": ""},
        "R10_LED_INTENSITY": {"min": 15, "max": 180, "unit": ""},
        "R11_LED_RED": {"min": 15, "max": 200, "unit": ""},
        "R11_LED_GREEN": {"min": 15, "max": 200, "unit": ""},
        "R11_LED_BLUE": {"min": 15, "max": 180, "unit": ""},
        "R11_LED_INTENSITY": {"min": 20, "max": 210, "unit": ""},
        "R12_LED_RED": {"min": 20, "max": 210, "unit": ""},
        "R12_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "R12_LED_BLUE": {"min": 30, "max": 200, "unit": ""},
        "R12_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "R13_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R13_LED_GREEN": {"min": 20, "max": 210, "unit": ""},
        "R13_LED_BLUE": {"min": 20, "max": 190, "unit": ""},
        "R13_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R14_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R14_LED_GREEN": {"min": 30, "max": 220, "unit": ""},
        "R14_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R14_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "R15_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R15_LED_GREEN": {"min": 30, "max": 210, "unit": ""},
        "R15_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R15_LED_INTENSITY": {"min": 20, "max": 210, "unit": ""},
        "R16_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R16_LED_GREEN": {"min": 30, "max": 200, "unit": ""},
        "R16_LED_BLUE": {"min": 20, "max": 190, "unit": ""},
        "R16_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R17_LED_RED": {"min": 15, "max": 200, "unit": ""},
        "R17_LED_GREEN": {"min": 20, "max": 200, "unit": ""},
        "R17_LED_BLUE": {"min": 15, "max": 180, "unit": ""},
        "R17_LED_INTENSITY": {"min": 20, "max": 200, "unit": ""},
        "R18_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "R18_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "R18_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R18_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R19_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R19_LED_GREEN": {"min": 15, "max": 220, "unit": ""},
        "R19_LED_BLUE": {"min": 15, "max": 190, "unit": ""},
        "R19_LED_INTENSITY": {"min": 15, "max": 210, "unit": ""},
        "R20_LED_RED": {"min": 15, "max": 180, "unit": ""},
        "R20_LED_GREEN": {"min": 15, "max": 180, "unit": ""},
        "R20_LED_BLUE": {"min": 15, "max": 150, "unit": ""},
        "R20_LED_INTENSITY": {"min": 15, "max": 190, "unit": ""},
        "L1_LED_RED": {"min": 20, "max": 210, "unit": ""},
        "L1_LED_GREEN": {"min": 40, "max": 210, "unit": ""},
        "L1_LED_BLUE": {"min": 30, "max": 210, "unit": ""},
        "L1_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "L2_LED_RED": {"min": 15, "max": 180, "unit": ""},
        "L2_LED_GREEN": {"min": 15, "max": 190, "unit": ""},
        "L2_LED_BLUE": {"min": 15, "max": 170, "unit": ""},
        "L2_LED_INTENSITY": {"min": 15, "max": 180, "unit": ""},
        "L3_LED_RED": {"min": 15, "max": 200, "unit": ""},
        "L3_LED_GREEN": {"min": 30, "max": 210, "unit": ""},
        "L3_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "L3_LED_INTENSITY": {"min": 40, "max": 220, "unit": ""},
        "L4_LED_RED": {"min": 15, "max": 170, "unit": ""},
        "L4_LED_GREEN": {"min": 20, "max": 180, "unit": ""},
        "L4_LED_BLUE": {"min": 15, "max": 160, "unit": ""},
        "L4_LED_INTENSITY": {"min": 20, "max": 170, "unit": ""},
        "L5_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "L5_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "L5_LED_BLUE": {"min": 30, "max": 220, "unit": ""},
        "L5_LED_INTENSITY": {"min": 40, "max": 220, "unit": ""},
        "L6_LED_RED": {"min": 15, "max": 180, "unit": ""},
        "L6_LED_GREEN": {"min": 15, "max": 180, "unit": ""},
        "L6_LED_BLUE": {"min": 15, "max": 170, "unit": ""},
        "L6_LED_INTENSITY": {"min": 15, "max": 190, "unit": ""},
        "L7_LED_RED": {"min": 20, "max": 210, "unit": ""},
        "L7_LED_GREEN": {"min": 40, "max": 210, "unit": ""},
        "L7_LED_BLUE": {"min": 30, "max": 200, "unit": ""},
        "L7_LED_INTENSITY": {"min": 40, "max": 210, "unit": ""},
        "OFF_LED_RED": {"min": 0, "max": 3, "unit": ""},
        "OFF_LED_GREEN": {"min": 0, "max": 3, "unit": ""},
        "OFF_LED_BLUE": {"min": 0, "max": 3, "unit": ""},
        "OFF_LED_INTENSITY": {"min": 0, "max": 3, "unit": ""},
        "SEGMENT_DIM_CHECK_1": {"min": 0, "max": 50, "unit": ""},
        "SEGMENT_DIM_CHECK_2": {"min": 0, "max": 50, "unit": ""},
        "RING_LED_LEAKAGE": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_1": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_2": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_3": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_4": {"min": 0, "max": 10, "unit": ""},
        "LED_POSITION_1": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_2": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_3": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_4": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_5": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_6": {"min": "", "max": "", "unit": ""},
        "SET_CONTROL_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "READ_CONTROL_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "SET_ENGINE_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "READ_ENGINE_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_holder_MT7VC": {
        "TBBUID": {"min": "", "max": "", "unit": ""},
        "write_codentify_code_control": {"min": "", "max": "", "unit": ""},
        "write_codentify_code_engine": {"min": "", "max": "", "unit": ""},
        "init_motor": {"min": "True", "max": "True", "unit": ""},
        "detect_dut": {"min": "XXXXXXXX", "max": "XXXXXXXX", "unit": ""},
        "BATTERY_LEVEL_TEST": {"min": 2500, "max": 4200, "unit": voltage_mv},
        "READ_CODENTIFY": {"min": "", "max": "", "unit": ""},
        "HAPTICS_OFF_TEST": {"min": 0, "max": 140, "unit": acceleration},
        "READ_DUSN": {"min": "0041007A000400000000", "max": "0041007A0004FFFFFFFF", "unit": ""},
        "ACC_X_TEST": {"min": 0, "max": 300, "unit": acceleration},
        "ACC_Y_TEST": {"min": 0, "max": 300, "unit": acceleration},
        "ACC_Z_TEST": {"min": 700, "max": 1300, "unit": acceleration},
        "ANGULAR_X_TEST": {"min": 0, "max": 100, "unit": "mDPS"},
        "ANGULAR_Y_TEST": {"min": 0, "max": 100, "unit": "mDPS"},
        "ANGULAR_Z_TEST": {"min": 0, "max": 100, "unit": "mDPS"},
        "UNTOUCH0_TEST": {"min": 0, "max": 65535, "unit": "ADC"},
        "UNTOUCH1_TEST": {"min": 0, "max": 65535, "unit": "ADC"},
        "UNTOUCH2_TEST": {"min": 0, "max": 65535, "unit": "ADC"},
        "BUTTON0_TEST": {"min": 25, "max": 200, "unit": "ADC"},
        "BUTTON1_TEST": {"min": 25, "max": 200, "unit": "ADC"},
        "BUTTON2_TEST": {"min": 25, "max": 200, "unit": "ADC"},
        "HAPTICS_ON_TEST": {"min": 500, "max": 3050, "unit": acceleration},
        "PRECHECK_MT_MODE": {"min": "beef", "max": "beef", "unit": ""},
        "READ_TEMPERATURE": {"min": 15, "max": 40, "unit": temperature},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_holder_Event_log_Check": {
        "start_test": {"min": "", "max": "", "unit": ""},
        "scan_vsn": {"min": "", "max": "", "unit": ""},
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "scan_codentify": {"min": "", "max": "", "unit": ""},
        "read_codentify": {"min": "", "max": "", "unit": ""},
        "read_dusn_control": {
            "min": "0041007A000000000000",
            "max": "0041007AFFFFFFFFFFFF",
            "unit": "",
        },
        "read_dusn_engine": {
            "min": "00290063000000000000",
            "max": "00290063FFFFFFFFFFFF",
            "unit": "",
        },
        "read_fw_control": {"min": "124.5.0", "max": "124.5.0", "unit": ""},
        "read_fw_engine": {"min": "102.6.0", "max": "102.6.0", "unit": ""},
        "read_event_logs": {"min": "", "max": "", "unit": ""},
        "check_autostart_count": {"min": "8", "max": "12", "unit": ""},
        "check_start_reason": {"min": "1", "max": "1", "unit": ""},
        "check_stop_reason": {"min": "2", "max": "2", "unit": ""},
        "check_heating_duration": {"min": "366", "max": "366", "unit": ""},
        "check_pause_reason": {"min": "1", "max": "65535", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_holder_MT11C": {
        "TBBUID": {"min": "", "max": "", "unit": ""},
        "TEST_CAVITY": {"min": "", "max": "", "unit": ""},
        "CONTROL_PCA_DUSN": {"min": "0041007A000400000000", "max": "0041007A0004FFFFFFFF", "unit": ""},
        "ENGINE_PCA_DUSN": {"min": "00290063000400000000", "max": "002900630004FFFFFFFF", "unit": ""},
        "CHECK_CODENTIFY_CODE_CONTROL": {"min": "", "max": "", "unit": ""},
        "CHECK_CODENTIFY_CODE_ENGINE": {"min": "", "max": "", "unit": ""},
        "CONTROL_PCA_TIME_SYNCHRONIZATION": {"min": -20, "max": 20, "unit": time_s},
        "BATTERY_LEVEL_CHECK": {"min": 28, "max": 30, "unit": percent},  # need upd
        "CONTROL_PCA_MT_STATUS": {"min": "0000", "max": "0000", "unit": ""},
        "ENGINE_PCA_MT_STATUS": {"min": "0000", "max": "0000", "unit": ""},
        "CONTROL_PCA_SW_ID": {"min": 0, "max": 0, "unit": ""},
        "ENGINE_PCA_SW_ID": {"min": 1, "max": 1, "unit": ""},
        "CONTROL_LOCK_MODE_BEFORE": {"min": "0000", "max": "0000", "unit": ""},
        "STOP_CHARGING": {"min": "True", "max": "True", "unit": ""},
        "HEATING_STATUS": {"min": "True", "max": "True", "unit": ""},
        "CONTROL_SHIP_MODE_AFTER": {"min": "0102", "max": "0102", "unit": ""},
        "check_ship_mode": {"min": "True", "max": "True", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
}
Beta_Holder_engine = {
    "Beta_holder_MT7LED": {
        "Start_Button": {"min": "", "max": "", "unit": ""},
        "TBBUID": {"min": "", "max": "", "unit": "TBBUID"},
        "SCAN_VSN": {"min": "", "max": "", "unit": ""},
        "LOG_BUILD_NUMBER": {"min": "", "max": "", "unit": ""},
        "CONTROL_PCA_DUSN": {
            "min": "0041007a000000000000",
            "max": "0041007aFFFFFFFFFFFF",
            "unit": "",
        },
        "ENGINE_PCA_DUSN": {
            "min": "00290063000000000000",
            "max": "00290063FFFFFFFFFFFF",
            "unit": "",
        },
        "CONTROL_MT_MODE_STATE": {"min": "", "max": "", "unit": ""},
        "QUERY_DGS_LENS_COLOR": {"min": "", "max": "", "unit": ""},
        "PIL_LENS_COLOR": {"min": "", "max": "", "unit": ""},
        "COMPARE_COLOR_RESULT": {"min": "", "max": "", "unit": ""},
        "QUERY_EXISTING_CONFIGURATION_CODE": {"min": "", "max": "", "unit": ""},
        "WRITE_NVCM_CONFIGURATION_CODE": {"min": "", "max": "", "unit": ""},
        "QUERY_NVCM_CONFIGURATION_CODE": {"min": "", "max": "", "unit": ""},
        "WRITE_NVCM_LED_BRIGHTNESS": {"min": "", "max": "", "unit": ""},
        "QUERY_NVCM_LED_BRIGHTNESS": {"min": "", "max": "", "unit": ""},
        "R1_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R1_LED_GREEN": {"min": 15, "max": 210, "unit": ""},
        "R1_LED_BLUE": {"min": 15, "max": 190, "unit": ""},
        "R1_LED_INTENSITY": {"min": 15, "max": 220, "unit": ""},
        "R2_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "R2_LED_GREEN": {"min": 30, "max": 220, "unit": ""},
        "R2_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R2_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R3_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R3_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R3_LED_BLUE": {"min": 15, "max": 210, "unit": ""},
        "R3_LED_INTENSITY": {"min": 15, "max": 220, "unit": ""},
        "R4_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R4_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R4_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R4_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R5_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R5_LED_GREEN": {"min": 30, "max": 210, "unit": ""},
        "R5_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R5_LED_INTENSITY": {"min": 30, "max": 210, "unit": ""},
        "R6_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R6_LED_GREEN": {"min": 30, "max": 220, "unit": ""},
        "R6_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R6_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "R7_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R7_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R7_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R7_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R8_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "R8_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "R8_LED_BLUE": {"min": 30, "max": 220, "unit": ""},
        "R8_LED_INTENSITY": {"min": 40, "max": 220, "unit": ""},
        "R9_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R9_LED_GREEN": {"min": 20, "max": 220, "unit": ""},
        "R9_LED_BLUE": {"min": 15, "max": 190, "unit": ""},
        "R9_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R10_LED_RED": {"min": 15, "max": 190, "unit": ""},
        "R10_LED_GREEN": {"min": 15, "max": 180, "unit": ""},
        "R10_LED_BLUE": {"min": 15, "max": 170, "unit": ""},
        "R10_LED_INTENSITY": {"min": 15, "max": 180, "unit": ""},
        "R11_LED_RED": {"min": 15, "max": 200, "unit": ""},
        "R11_LED_GREEN": {"min": 15, "max": 200, "unit": ""},
        "R11_LED_BLUE": {"min": 15, "max": 180, "unit": ""},
        "R11_LED_INTENSITY": {"min": 20, "max": 210, "unit": ""},
        "R12_LED_RED": {"min": 20, "max": 210, "unit": ""},
        "R12_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "R12_LED_BLUE": {"min": 30, "max": 200, "unit": ""},
        "R12_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "R13_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R13_LED_GREEN": {"min": 20, "max": 210, "unit": ""},
        "R13_LED_BLUE": {"min": 20, "max": 190, "unit": ""},
        "R13_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R14_LED_RED": {"min": 15, "max": 220, "unit": ""},
        "R14_LED_GREEN": {"min": 30, "max": 220, "unit": ""},
        "R14_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R14_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "R15_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R15_LED_GREEN": {"min": 30, "max": 210, "unit": ""},
        "R15_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "R15_LED_INTENSITY": {"min": 20, "max": 210, "unit": ""},
        "R16_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R16_LED_GREEN": {"min": 30, "max": 200, "unit": ""},
        "R16_LED_BLUE": {"min": 20, "max": 190, "unit": ""},
        "R16_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R17_LED_RED": {"min": 15, "max": 200, "unit": ""},
        "R17_LED_GREEN": {"min": 20, "max": 200, "unit": ""},
        "R17_LED_BLUE": {"min": 15, "max": 180, "unit": ""},
        "R17_LED_INTENSITY": {"min": 20, "max": 200, "unit": ""},
        "R18_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "R18_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "R18_LED_BLUE": {"min": 20, "max": 210, "unit": ""},
        "R18_LED_INTENSITY": {"min": 20, "max": 220, "unit": ""},
        "R19_LED_RED": {"min": 15, "max": 210, "unit": ""},
        "R19_LED_GREEN": {"min": 15, "max": 220, "unit": ""},
        "R19_LED_BLUE": {"min": 15, "max": 190, "unit": ""},
        "R19_LED_INTENSITY": {"min": 15, "max": 210, "unit": ""},
        "R20_LED_RED": {"min": 15, "max": 180, "unit": ""},
        "R20_LED_GREEN": {"min": 15, "max": 180, "unit": ""},
        "R20_LED_BLUE": {"min": 15, "max": 150, "unit": ""},
        "R20_LED_INTENSITY": {"min": 15, "max": 190, "unit": ""},
        "L1_LED_RED": {"min": 20, "max": 210, "unit": ""},
        "L1_LED_GREEN": {"min": 40, "max": 210, "unit": ""},
        "L1_LED_BLUE": {"min": 30, "max": 210, "unit": ""},
        "L1_LED_INTENSITY": {"min": 30, "max": 220, "unit": ""},
        "L2_LED_RED": {"min": 15, "max": 180, "unit": ""},
        "L2_LED_GREEN": {"min": 15, "max": 190, "unit": ""},
        "L2_LED_BLUE": {"min": 15, "max": 170, "unit": ""},
        "L2_LED_INTENSITY": {"min": 15, "max": 180, "unit": ""},
        "L3_LED_RED": {"min": 15, "max": 200, "unit": ""},
        "L3_LED_GREEN": {"min": 30, "max": 210, "unit": ""},
        "L3_LED_BLUE": {"min": 20, "max": 200, "unit": ""},
        "L3_LED_INTENSITY": {"min": 40, "max": 220, "unit": ""},
        "L4_LED_RED": {"min": 15, "max": 170, "unit": ""},
        "L4_LED_GREEN": {"min": 20, "max": 180, "unit": ""},
        "L4_LED_BLUE": {"min": 15, "max": 160, "unit": ""},
        "L4_LED_INTENSITY": {"min": 20, "max": 170, "unit": ""},
        "L5_LED_RED": {"min": 20, "max": 220, "unit": ""},
        "L5_LED_GREEN": {"min": 40, "max": 220, "unit": ""},
        "L5_LED_BLUE": {"min": 30, "max": 220, "unit": ""},
        "L5_LED_INTENSITY": {"min": 40, "max": 220, "unit": ""},
        "L6_LED_RED": {"min": 15, "max": 180, "unit": ""},
        "L6_LED_GREEN": {"min": 15, "max": 180, "unit": ""},
        "L6_LED_BLUE": {"min": 15, "max": 170, "unit": ""},
        "L6_LED_INTENSITY": {"min": 15, "max": 190, "unit": ""},
        "L7_LED_RED": {"min": 20, "max": 210, "unit": ""},
        "L7_LED_GREEN": {"min": 40, "max": 210, "unit": ""},
        "L7_LED_BLUE": {"min": 30, "max": 200, "unit": ""},
        "L7_LED_INTENSITY": {"min": 40, "max": 210, "unit": ""},
        "OFF_LED_RED": {"min": 0, "max": 3, "unit": ""},
        "OFF_LED_GREEN": {"min": 0, "max": 3, "unit": ""},
        "OFF_LED_BLUE": {"min": 0, "max": 3, "unit": ""},
        "OFF_LED_INTENSITY": {"min": 0, "max": 3, "unit": ""},
        "SEGMENT_DIM_CHECK_1": {"min": 0, "max": 50, "unit": ""},
        "SEGMENT_DIM_CHECK_2": {"min": 0, "max": 50, "unit": ""},
        "RING_LED_LEAKAGE": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_1": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_2": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_3": {"min": 0, "max": 10, "unit": ""},
        "SEGMENT_LED_LEAKAGE_4": {"min": 0, "max": 10, "unit": ""},
        "LED_POSITION_1": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_2": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_3": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_4": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_5": {"min": "", "max": "", "unit": ""},
        "LED_POSITION_6": {"min": "", "max": "", "unit": ""},
        "SET_CONTROL_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "READ_CONTROL_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "SET_ENGINE_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "READ_ENGINE_PCBA_CODENTIFIER": {"min": "", "max": "", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_holder_MT11C": {
        "TBBUID": {"min": "", "max": "", "unit": ""},
        "TEST_CAVITY": {"min": "", "max": "", "unit": ""},
        "CONTROL_PCA_DUSN": {"min": "0041007A000400000000", "max": "0041007A0004FFFFFFFF", "unit": ""},
        "ENGINE_PCA_DUSN": {"min": "00290063000400000000", "max": "002900630004FFFFFFFF", "unit": ""},
        "CHECK_CODENTIFY_CODE_CONTROL": {"min": "", "max": "", "unit": ""},
        "CHECK_CODENTIFY_CODE_ENGINE": {"min": "", "max": "", "unit": ""},
        "CONTROL_PCA_TIME_SYNCHRONIZATION": {"min": -20, "max": 20, "unit": time_s},
        "BATTERY_LEVEL_CHECK": {"min": 28, "max": 30, "unit": percent},  # need upd
        "ENGINE_PCA_MT_STATUS": {"min": "0000", "max": "0000", "unit": ""},
        "CONTROL_PCA_SW_ID": {"min": 0, "max": 0, "unit": ""},
        "ENGINE_PCA_SW_ID": {"min": 1, "max": 1, "unit": ""},
        "CONTROL_LOCK_MODE_BEFORE": {"min": "0000", "max": "0000", "unit": ""},
        "CONTROL_SHIP_MODE_AFTER": {"min": "0102", "max": "0102", "unit": ""},
        "check_ship_mode": {"min": "True", "max": "True", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Beta_MT1_holder_control": {
        "TBBUID": {"min": "", "max": "", "unit": ""},
        "mt1_ask_question": {"equal": "True", "unit": ""},
        "detect_dut": {"equal": "XXXXXXXX", "unit": ""},
        "write_dusn_control": {"equal": "0041007aFFFFFFFFFFFFXXXX", "unit": ""},
        "write_dusn_engine": {"equal": "00290063FFFFFFFFFFFFXXXX", "unit": ""},
        "check_authentication_control_key0": {"equal": "44988", "unit": ""},
        "check_authentication_control_key1": {"equal": "7116", "unit": ""},
        "check_authentication_engine_key0": {"equal": "56001", "unit": ""},
        "check_authentication_engine_key1": {"equal": "30164", "unit": ""},
        "write_authentication_key_engine": {"equal": "True", "unit": ""},
        "check_authentication_control": {"equal": "True", "unit": ""},
        "check_authentication_engine": {"equal": "True", "unit": ""},
        "fuel_program": {"equal": "True", "unit": ""},
        "fuel_functional_test": {"equal": "True", "unit": ""},
        "OVERALL_TEST_RESULT": {"equal": "0", "unit": "TR"},
    },
}
eaglemono = {
    "Eaglemono_MT1": {
        "TBBUID": {"min": "", "max": "", "unit": ""},
        "TEST_CAVITY": {"min": "", "max": "", "unit": ""},
        "power_on": {"min": "", "max": "", "unit": ""},
        "power_on_current": {"min": "", "max": "", "unit": ""},
        "power_on_voltage": {"min": -20, "max": 20, "unit": ""},
        "mcu_program": {"min": 28, "max": 30, "unit": ""},
        "fw_check": {"min": "", "max": "", "unit": ""},
        "bist_test": {"min": "0000", "max": "0000", "unit": ""},
        "heater_enablement_power_on": {"min": 0, "max": 0, "unit": ""},
        "heater_enablement_power_off": {"min": 1, "max": 1, "unit": ""},
        "vdd3_power_on": {"min": "0000", "max": "0000", "unit": ""},
        "vdd3_power_off": {"min": "True", "max": "True", "unit": ""},
        "vio_power_on": {"min": "True", "max": "True", "unit": ""},
        "vio_power_off": {"min": "0102", "max": "0102", "unit": ""},
        "vddusb_power_on": {"min": "True", "max": "True", "unit": ""},
        "vddusb_power_off": {"min": "", "max": "", "unit": ""},
        "vd18_power_on": {"min": "", "max": "", "unit": ""},
        "vd18_power_off": {"min": "", "max": "", "unit": ""},
        "vd11_power_on": {"min": "", "max": "", "unit": ""},
        "vd11_power_off": {"min": "", "max": "", "unit": ""},
        "tac_1v8_power_on": {"min": "", "max": "", "unit": ""},
        "tac_1v8_power_off": {"min": "", "max": "", "unit": ""},
        "tac_2v8_power_on": {"min": "", "max": "", "unit": ""},
        "tac_2v8_power_off": {"min": "", "max": "", "unit": ""},
        "vboost_out_power_on": {"min": "", "max": "", "unit": ""},
        "vboost_out_power_off": {"min": "", "max": "", "unit": ""},
        "dp2v5_power_on": {"min": "", "max": "", "unit": ""},
        "dp2v5_power_off": {"min": "", "max": "", "unit": ""},
        "dp3v5_power_on": {"min": "", "max": "", "unit": ""},
        "dp3v5_power_off": {"min": "", "max": "", "unit": ""},
        "vm_power_on": {"min": "", "max": "", "unit": ""},
        "vm_power_off": {"min": "", "max": "", "unit": ""},
        "vbus_power_on": {"min": "", "max": "", "unit": ""},
        "vbus_power_off": {"min": "", "max": "", "unit": ""},
        "button_status_off": {"min": "", "max": "", "unit": ""},
        "button_status_on": {"min": "", "max": "", "unit": ""},
        "button_reset_test": {"min": "", "max": "", "unit": ""},
        "pre_charge_current": {"min": "", "max": "", "unit": ""},
        "fast_charge_current": {"min": "", "max": "", "unit": ""},
        "current_after_stop": {"min": "", "max": "", "unit": ""},
        "disable_charge_current": {"min": "", "max": "", "unit": ""},
        "haptic_on": {"min": "", "max": "", "unit": ""},
        "haptic_off": {"min": "", "max": "", "unit": ""},
        "imu_test": {"min": "", "max": "", "unit": ""},
        "RT200_temperature": {"min": "", "max": "", "unit": ""},
        "RT500_temperature": {"min": "", "max": "", "unit": ""},
        "Hall_sensor_on": {"min": "", "max": "", "unit": ""},
        "Hall_sensor_off": {"min": "", "max": "", "unit": ""},
        "sleep_enter": {"min": "", "max": "", "unit": ""},
        "sleep_exit": {"min": "", "max": "", "unit": ""},
        "ship_mode_enter": {"min": "", "max": "", "unit": ""},
        "WRITE_PCA_DUSN": {"min": "0041007A000400000000", "max": "0041007A0004FFFFFFFF", "unit": ""},
        "READ_PCA_DUSN": {"min": "00290063000400000000", "max": "002900630004FFFFFFFF", "unit": ""},
        "OVERALL_TEST_RESULT": {"min": "0", "max": "0", "unit": "TR"},
    },
    "Eaglemono_MT10": {
                "TBBUID": {"min": "", "max": "", "unit": ""},
                "mt1_ask_question": {"equal": "True", "unit": ""},
                "detect_dut": {"equal": "XXXXXXXX", "unit": ""},
                "write_dusn_control": {"equal": "0041007aFFFFFFFFFFFFXXXX", "unit": ""},
                "write_dusn_engine": {"equal": "00290063FFFFFFFFFFFFXXXX", "unit": ""},
                "check_authentication_control_key0": {"equal": "44988", "unit": ""},
                "check_authentication_control_key1": {"equal": "7116", "unit": ""},
                "check_authentication_engine_key0": {"equal": "56001", "unit": ""},
                "check_authentication_engine_key1": {"equal": "30164", "unit": ""},
                "write_authentication_key_engine": {"equal": "True", "unit": ""},
                "check_authentication_control": {"equal": "True", "unit": ""},
                "check_authentication_engine": {"equal": "True", "unit": ""},
                "fuel_program": {"equal": "True", "unit": ""},
                "fuel_functional_test": {"equal": "True", "unit": ""},
                "OVERALL_TEST_RESULT": {"equal": "0", "unit": "TR"},
    },

}
rd = {"rd_MT0": {"rd_loop_test": {"min": "", "max": "", "unit": ""}}}
